import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { quicktype, InputData, JSONSchemaInput, FetchingJSONSchemaStore } from 'quicktype-core';

const base = new URL('../', import.meta.url);
const source = await readFile(new URL('schemas/v1/contracts.json', base), 'utf8');
const schema = JSON.parse(source);
const input = new JSONSchemaInput(new FetchingJSONSchemaStore());
for (const name of Object.keys(schema.definitions).filter((name) => !['Id', 'Counter'].includes(name))) {
  await input.addSource({ name, schema: JSON.stringify({ ...schema, $ref: `#/definitions/${name}` }) });
}
const inputData = new InputData();
inputData.addInput(input);
const artifacts = new Map();
for (const [lang, output, rendererOptions] of [
  ['typescript', 'generated/types.ts', { 'just-types': 'true', 'prefer-unions': 'true' }],
  ['go', 'generated/go/types.go', { package: 'protocol', 'just-types': 'true' }],
]) {
  const result = await quicktype({ inputData, lang, rendererOptions });
  artifacts.set(output, `// Generated by pnpm protocol:generate; edit schemas/v1/contracts.json.\n${lang === 'go' ? 'package protocol\n\n' : ''}${result.lines.join('\n').trimEnd()}\n`);
}
artifacts.set('generated/go/go.mod', 'module monolab.local/protocol\n\ngo 1.24.0\n');
artifacts.set('generated/go/contracts.json', source);
artifacts.set('generated/go/schema.go', '// Generated by pnpm protocol:generate.\npackage protocol\n\nimport _ "embed"\n\n// SchemaJSON is the authoritative versioned wire schema.\n//go:embed contracts.json\nvar SchemaJSON []byte\n');
const reference = (name) => ({ $ref: `#/components/schemas/${name}` });
const responses = (name) => ({
  200: { description: 'Authenticated response; admission is distinct from completed effects.', content: { 'application/json': { schema: reference(name) } } },
  default: { description: 'Deterministic protocol error.', content: { 'application/json': { schema: reference('CommandResult') } } },
});
const security = (auth) => auth === 'OwnerAuth' ? [{ OwnerAuth: [] }, { OwnerCookie: [] }] : [{ [auth]: [] }];
const get = (name, auth, parameters = []) => ({ security: security(auth), parameters: parameters.map((name) => ({ name, in: 'path', required: true, schema: reference('Id') })), responses: responses(name) });
artifacts.set('generated/openapi.json', `${JSON.stringify({
  openapi: '3.1.0', info: { title: 'MonoLab boundary probe', version: '1.0.0' },
  paths: {
    '/v1/owner/login': { post: { description: 'Same-origin password login; sets Secure HttpOnly __Host-monolab cookie.', requestBody: { required: true, content: { 'application/json': { schema: reference('OwnerLogin') } } }, responses: responses('OwnerSessionStatus') } },
    '/v1/owner/session': { get: get('OwnerSessionStatus', 'OwnerAuth') },
    '/v1/owner/logout': { post: { security: security('OwnerAuth'), description: 'Revokes current session and clears its cookie; cookie writes require same Origin.', responses: responses('OwnerSessionStatus') } },
    '/v1/owner/tasks/{task_id}': { get: get('TaskOverview', 'OwnerAuth', ['task_id']) },
    '/v1/owner/tasks/{task_id}/events': { get: { ...get('TaskEventPage', 'OwnerAuth', ['task_id']), parameters: [...get('TaskEventPage', 'OwnerAuth', ['task_id']).parameters, { name: 'cursor', in: 'query', required: false, schema: reference('TaskEventCursor') }] } },
    '/v1/owner/commands': { post: { security: security('OwnerAuth'), requestBody: { required: true, content: { 'application/json': { schema: reference('OwnerCommand') } } }, responses: responses('OwnerCommandResult') } },
    '/v1/owner/scopes/{scope_id}/commands/{request_id}': { get: get('OwnerCommandResult', 'OwnerAuth', ['scope_id', 'request_id']) },
    '/v1/commands': { post: { security: [{ AttemptAuth: [] }], requestBody: { required: true, content: { 'application/json': { schema: reference('CommandSubmission') } } }, responses: responses('CommandResult') } },
    '/v1/commands/{request_id}': { get: get('CommandResult', 'AttemptAuth', ['request_id']) },
    '/v1/runner/inventory': { get: { ...get('RunnerInventory', 'RunnerAuth'), parameters: Object.entries(schema.definitions.InventoryQuery.properties).map(([name, shape]) => ({ name, in: 'query', required: false, description: 'Cursor and snapshot_id must be supplied together; restart the entire scan on snapshot conflict.', schema: JSON.parse(JSON.stringify(shape).replaceAll('#/definitions/', '#/components/schemas/')) })) } },
    '/v1/recovery/attempts/{attempt_id}/commands/{request_id}': { get: get('CommandResult', 'RunnerAuth', ['attempt_id', 'request_id']) },
    '/v1/recovery/operations/{operation_id}': { get: get('Operation', 'RunnerAuth', ['operation_id']) },
  },
  components: { schemas: JSON.parse(JSON.stringify(schema.definitions).replaceAll('#/definitions/', '#/components/schemas/')), securitySchemes: { OwnerCookie: { type: 'apiKey', in: 'cookie', name: '__Host-monolab', description: 'Secure HttpOnly Owner session; state-changing requests require same Origin.' }, OwnerAuth: { type: 'http', scheme: 'bearer', description: 'Opaque Owner session; neither Runner nor Attempt credentials are accepted.' }, AttemptAuth: { type: 'http', scheme: 'bearer', description: 'Attempt-scoped credential; never a Runner token.' }, RunnerAuth: { type: 'http', scheme: 'bearer', description: 'Service-private enrolled Runner identity.' } } },
}, null, 2)}\n`);
for (const [relative, content] of artifacts) {
  const path = new URL(relative, base);
  if (process.argv.includes('--check')) {
    if (await readFile(path, 'utf8').catch(() => '') !== content) throw new Error(`Generated drift: ${relative}`);
  } else {
    await mkdir(fileURLToPath(new URL('.', path)), { recursive: true });
    await writeFile(path, content);
  }
}
console.log(process.argv.includes('--check') ? 'Protocol generation is current.' : 'Generated TS and Go protocol types.');
