import { useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import type { ConfigurationResult, ConfigurationSnapshot, GitHubRepositoryPage, GitRepositoryResource, ProjectConfiguration } from '../../../../packages/protocol/generated/types.ts';
import { Button } from '../components/ui/button.tsx';
import { EditorActions, Field, PageHeading, Select } from '../components/forms.tsx';
import type { Draft, Save } from '../components/forms.tsx';
import { request } from '../lib/api.ts';

export function Projects({ snapshot, save, disabled, committed }: { snapshot: ConfigurationSnapshot; save: Save; disabled: boolean; committed?: ConfigurationResult }) {
  const [selected, setSelected] = useState<string>();
  const [drafts, setDrafts] = useState<Record<string, Draft<ProjectConfiguration>>>({});
  useEffect(() => { if (committed?.entity_id) setDrafts((all) => { const next = { ...all }; delete next[committed.entity_id!]; return next; }); }, [committed]);
  const [picker, setPicker] = useState(false); const [page, setPage] = useState(1);
  const repositories = useQuery({ queryKey: ['github-repositories', snapshot.control_version, page], queryFn: () => request<GitHubRepositoryPage>(`/v1/owner/github/repositories?page=${page}`, 'GitHubRepositoryPage'), enabled: picker && !!snapshot.github, retry: false });
  const id = selected ?? snapshot.projects[0]?.id; const saved = snapshot.projects.find((project) => project.id === id);
  const draft = id ? drafts[id] ?? (saved ? { value: saved, basis: snapshot.control_version } : undefined) : undefined;
  function update(value: ProjectConfiguration) { setDrafts((all) => ({ ...all, [value.id]: { value, basis: draft?.basis ?? snapshot.control_version } })); }
  function create() { const value: ProjectConfiguration = { id: crypto.randomUUID(), name: '', context: '', resources: [], role_ids: [], archived: false }; setDrafts((all) => ({ ...all, [value.id]: { value, basis: snapshot.control_version } })); setSelected(value.id); }
  function clear() { if (id) setDrafts((all) => { const next = { ...all }; delete next[id]; return next; }); }
  function resource(index: number, value: GitRepositoryResource) { if (draft) update({ ...draft.value, resources: draft.value.resources.map((row, i) => i === index ? value : row) }); }
  const rows = [...snapshot.projects, ...Object.values(drafts).filter((row) => !snapshot.projects.some((p) => p.id === row.value.id)).map((row) => row.value)];
  return <><PageHeading title="Projects" description="Give your work a home, context, and the right resources." action={<Button disabled={disabled} onClick={create}>New project</Button>} />
    <div className="split-view"><aside className="record-list" aria-label="Project list">{rows.map((project) => <button type="button" key={project.id} className={id === project.id ? 'record selected' : 'record'} onClick={() => setSelected(project.id)}><span>{drafts[project.id]?.value.name || project.name || 'Untitled project'}</span><small>{project.archived ? 'Archived' : `${project.resources.length} repositories`}{drafts[project.id] ? ' · Draft' : ''}</small></button>)}{!rows.length && <p className="empty-list">Your Projects will appear here.</p>}</aside>
      {draft ? <form className="editor card" onSubmit={async (event) => { event.preventDefault(); if (await save('save_project', draft.value, draft.basis)) clear(); }}><fieldset disabled={disabled}><div className="section-label"><h2>Project details</h2><span className="tag">{draft.value.archived ? 'Archived' : 'Active'}</span></div>
        <Field label="Project name" value={draft.value.name} onChange={(name) => update({ ...draft.value, name })} required maxLength={200} placeholder="e.g. Personal website" />
        <Field label="Project context" multiline rows={6} value={draft.value.context} onChange={(context) => update({ ...draft.value, context })} maxLength={64000} hint="Your project description, technical constraints, and delivery conventions." />
        <section className="subsection"><div className="section-label"><div><h3>Repositories</h3><p className="hint">Agents open these resources when their work needs them.</p></div></div>
          {draft.value.resources.map((repo, index) => <div className="resource" key={repo.id}><div className="resource-heading"><strong>Repository {index + 1}</strong><Button type="button" variant="ghost" onClick={() => update({ ...draft.value, resources: draft.value.resources.filter((r) => r.id !== repo.id) })}>Remove repository {index + 1}</Button></div>
            <Field label={`Repository ${index + 1} remote URL`} value={repo.remote_url} required maxLength={2048} readOnly={!!saved?.resources.some((r) => r.id === repo.id)} hint={saved?.resources.some((r) => r.id === repo.id) ? 'Saved repository identity is fixed. Add another resource to use a different remote.' : 'HTTPS or SSH Git URL. No embedded access tokens.'} onChange={(remote_url) => resource(index, { ...repo, remote_url })} />
            <div className="field-grid"><Field label={`Repository ${index + 1} default ref`} value={repo.default_ref ?? ''} maxLength={256} placeholder="Repository default" onChange={(value) => { const rest = { ...repo }; delete rest.default_ref; resource(index, value ? { ...rest, default_ref: value } : rest); }} /><Field label={`Repository ${index + 1} target branch`} value={repo.default_branch ?? ''} maxLength={256} placeholder="Repository default" onChange={(value) => { const rest = { ...repo }; delete rest.default_branch; resource(index, value ? { ...rest, default_branch: value } : rest); }} />
            <Select label={`Repository ${index + 1} remote preparation`} value={repo.remote_preparation} onChange={(event) => resource(index, { ...repo, remote_preparation: event.target.value === 'automatic' ? 'automatic' : 'after_acceptance' })}><option value="automatic">When ready for review</option><option value="after_acceptance">After Owner acceptance</option></Select>
            <Select label={`Repository ${index + 1} merge method`} value={repo.merge_method ?? ''} onChange={(event) => { const rest = { ...repo }; delete rest.merge_method; const value = event.target.value; resource(index, value === 'merge' || value === 'squash' || value === 'rebase' ? { ...rest, merge_method: value } : rest); }}><option value="">Repository default</option><option value="merge">Merge commit</option><option value="squash">Squash</option><option value="rebase">Rebase</option></Select></div>
          </div>)}
          <div className="button-row"><Button type="button" variant="outline" onClick={() => update({ ...draft.value, resources: [...draft.value.resources, { id: crypto.randomUUID(), remote_url: '', remote_preparation: 'automatic' }] })}>Add Git repository</Button><Button type="button" variant="outline" disabled={!snapshot.github} onClick={() => setPicker(!picker)}>{picker ? 'Close GitHub picker' : 'Choose from GitHub'}</Button></div>
          {!snapshot.github && <p className="hint">Connect a GitHub App in GitHub settings to choose authorized repositories.</p>}
          {picker && <div className="repository-picker" aria-label="GitHub repositories">{repositories.isPending && <p>Loading repositories…</p>}{repositories.error && <p role="alert">{repositories.error.message}</p>}{repositories.data?.repositories.map((repo) => <button key={repo.provider_repo_id} type="button" className="repository-choice" onClick={() => { update({ ...draft.value, resources: [...draft.value.resources, { id: crypto.randomUUID(), remote_url: repo.remote_url, default_branch: repo.default_branch, remote_preparation: 'automatic', provider: 'github', provider_repo_id: repo.provider_repo_id }] }); setPicker(false); }}>{repo.full_name}<small>{repo.private ? 'Private' : 'Public'}</small></button>)}{repositories.data?.repositories.length === 0 && <p>No authorized repositories on this page.</p>}<div className="button-row"><Button type="button" variant="ghost" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous page</Button><Button type="button" variant="ghost" disabled={!repositories.data?.next_page} onClick={() => setPage(repositories.data?.next_page ?? page)}>Next page</Button></div></div>}
        </section>
        <section className="subsection"><h3>Available roles</h3><p className="hint">Planner can choose from the reusable roles you select.</p>{snapshot.roles.filter((role) => !role.archived || draft.value.role_ids.includes(role.id)).map((role) => <label className="checkbox" key={role.id}><input type="checkbox" checked={draft.value.role_ids.includes(role.id)} onChange={(event) => update({ ...draft.value, role_ids: event.target.checked ? [...draft.value.role_ids, role.id] : draft.value.role_ids.filter((id) => id !== role.id) })} /><span>{role.name}{role.archived ? ' (hidden)' : ''}</span></label>)}{!snapshot.roles.length && <p className="inline-note">Create a reusable Role first, then select it here.</p>}</section>
        <label className="checkbox"><input type="checkbox" checked={draft.value.archived} onChange={(event) => update({ ...draft.value, archived: event.target.checked })} />Archive Project</label>
        <EditorActions dirty={!!(id && drafts[id])} disabled={disabled} reload={() => { clear(); if (!saved) setSelected(undefined); }} />
      </fieldset></form> : <div className="card empty-state"><span className="empty-symbol" aria-hidden="true">↗</span><h2>Make room for your next idea.</h2><p>Create a Project with the context, repositories, and roles your agents will use.</p><Button onClick={create}>Create your first project</Button></div>}
    </div></>;
}
